project4:project4.o AutoIns.o HomeIns.o LifeIns.o Manager.o\
	 Salesperson.o Employee.o Policy.o
	g++ AutoIns.o HomeIns.o project4.o LifeIns.o Manager.o\
	 Salesperson.o Employee.o Policy.o -o project4

project4.o:project4.cpp
	g++ -c project4.cpp

AutoIns.o:AutoIns.cpp AutoIns.h
	g++ -c AutoIns.cpp

HomeIns.o:HomeIns.cpp HomeIns.h
	g++ -c HomeIns.cpp

LifeIns.o:LifeIns.cpp LifeIns.h
	g++ -c LifeIns.cpp

Manager.o:Manager.cpp Manager.h
	g++ -c Manager.cpp

Salesperson.o:Salesperson.cpp Salesperson.h
	g++ -c Salesperson.cpp

Employee.o:Employee.cpp Employee.h
	g++ -c Employee.cpp

Policy.o:Policy.cpp Policy.h
	g++ -c Policy.cpp
